export const CLEAR_ALERT = "CLEAR_ALERT";
export const DISPLAY_ALERT = "DISPLAY_ALERT";
export const VERIFICATION_EMAIL_SENT = "VERIFICATION_EMAIL_SENT";
export const HANDLE_CHANGE = "HANDLE_CHANGE";

export const REGISTER_USER_BEGIN = "REGISTER_USER_BEGIN";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_ERROR = "REGISTER_USER_ERROR";

export const LOGIN_USER_BEGIN = "LOGIN_USER_BEGIN";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_ERROR = "LOGIN_USER_ERROR";

export const VERIFICATION_BEGINS = "VERIFICATION_BEGINS";
export const VERIFICATION_SUCCESS = "VERIFICATION_SUCCESS";
export const VERIFICATION_ERROR = "VERIFICATION_ERROR";

export const CREATE_NOTE_BEGINS = "CREATE_NOTE_BEGINS";
export const CREATE_NOTE_SUCCESS = "CREATE_NOTE_SUCCESS";
export const CREATE_NOTE_ERROR = "CREATE_NOTE_ERROR";

export const SET_EDIT_NOTE = "SET_EDIT_NOTE";

export const EDIT_NOTE_BEGINS = "EDIT_NOTE_BEGINS";
export const EDIT_NOTE_SUCCESS = "EDIT_NOTE_SUCCESS";
export const EDIT_NOTE_ERROR = "EDIT_NOTE_ERROR";

export const GET_ALL_NOTES_BEGINS = "GET_ALL_NOTES_BEGIN";
export const GET_ALL_NOTES_SUCCESS = "GET_ALL_NOTES_SUCCESS";
export const GET_ALL_NOTES_ERROR = "GET_ALL_NOTES_ERROR";

export const DELETE_NOTE_BEGINS = "DELETE_NOTE_BEGINS";
export const DELETE_NOTE_SUCCESS = "DELETE_NOTE_SUCCESS";
export const DELETE_NOTE_ERROR = "DELETE_NOTE_ERROR";

export const TOGGLE_SIDEBAR = "TOGGLE_SIDEBAR";
export const CHANGE_PAGE = "CHANGE_PAGE";

export const LOGOUT_USER = "LOGOUT_USER";
